"""BULL public API: artifact compatibility plus typed BULL Core contracts."""

from .schemas import (
    BENCH_CHECKPOINT_SCHEMA_VERSION,
    BENCH_CONFIG_SCHEMA_VERSION,
    BENCH_RECORD_SCHEMA_VERSION,
    BENCH_SPEC_SCHEMA_VERSION,
    BENCH_SUMMARY_SCHEMA_VERSION,
    PROMPT_INDEX_SCHEMA,
    PROMPT_INDEX_SCHEMA_VERSION,
    TESTED_PROFILE_SCHEMA,
    TESTED_PROFILE_SCHEMA_VERSION,
    USER_BENCHMARK_SCHEMA,
    USER_BENCHMARK_SCHEMA_VERSION,
)
from .compatibility import (
    CompatibilityInfo,
    inspect_legacy_document,
    read_legacy_artifact,
    supported_legacy_artifacts,
)
from .core import (
    ArtifactClassification,
    ArtifactStore,
    AtomicArtifactStore,
    BackendAdapter,
    BackendCapabilities,
    BackendKind,
    BenchmarkCase,
    BenchmarkPack,
    ChatMessage,
    GenerationRequest,
    GenerationResponse,
    InferenceEvent,
    InferenceEventKind,
    ModelDescriptor,
    ReportRenderer,
    Runner,
    SchemaMigration,
    ScoreResult,
    Scorer,
    TelemetryProvider,
    Verifier,
)

__all__ = [name for name in globals() if name.isupper() or name in {
    "CompatibilityInfo",
    "inspect_legacy_document",
    "read_legacy_artifact",
    "supported_legacy_artifacts",
    "ArtifactClassification",
    "ArtifactStore",
    "AtomicArtifactStore",
    "BackendAdapter",
    "BackendCapabilities",
    "BackendKind",
    "BenchmarkCase",
    "BenchmarkPack",
    "ChatMessage",
    "GenerationRequest",
    "GenerationResponse",
    "InferenceEvent",
    "InferenceEventKind",
    "ModelDescriptor",
    "ReportRenderer",
    "Runner",
    "SchemaMigration",
    "ScoreResult",
    "Scorer",
    "TelemetryProvider",
    "Verifier",
}]
