"""Version numbers shared by Benchmark Lab and the working Client."""

BENCH_CONFIG_SCHEMA_VERSION=3
BENCH_SPEC_SCHEMA_VERSION=9
BENCH_RECORD_SCHEMA_VERSION=12
BENCH_SUMMARY_SCHEMA_VERSION=11
BENCH_CHECKPOINT_SCHEMA_VERSION=9
TESTED_PROFILE_SCHEMA='bull-tested-profiles'
TESTED_PROFILE_SCHEMA_VERSION=1
PROMPT_INDEX_SCHEMA='bull-prompt-index'
PROMPT_INDEX_SCHEMA_VERSION=2
USER_BENCHMARK_SCHEMA='bull-user-benchmark'
USER_BENCHMARK_SCHEMA_VERSION=1
BULL_RECORD_SCHEMA='bull-benchmark-record'
BULL_RECORD_SCHEMA_VERSION=1
BULL_SUMMARY_SCHEMA='bull-benchmark-summary'
BULL_SUMMARY_SCHEMA_VERSION=1
BULL_PROVENANCE_SCHEMA='bull-evidence-provenance'
BULL_PROVENANCE_SCHEMA_VERSION=1
